-- Namespaced schema for the existing hair-by-maeva Supabase project.
-- The project already contains legacy `services` and `bookings` tables, so this
-- avoids changing or deleting existing data.
create extension if not exists pgcrypto;
create type public.hm_booking_status as enum ('pending_payment','payment_submitted','confirmed','completed','cancelled','rescheduled');
create type public.hm_payment_status as enum ('unpaid','payment_submitted','payment_verified','payment_not_received');

create table if not exists public.hm_customers (id uuid primary key default gen_random_uuid(), full_name text not null, email text not null, phone text, location text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index if not exists hm_customers_email_lower_idx on public.hm_customers (lower(email));
create table if not exists public.hm_service_categories (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, is_active boolean not null default true, display_order int not null default 0);
create table if not exists public.hm_services (id uuid primary key default gen_random_uuid(), category_id uuid references public.hm_service_categories(id) on delete set null, name text not null, slug text not null unique, description text, duration_minutes int not null default 180 check(duration_minutes > 0), image_path text, is_active boolean not null default true, display_order int not null default 0);
create table if not exists public.hm_service_lengths (id uuid primary key default gen_random_uuid(), service_id uuid not null references public.hm_services(id) on delete cascade, name text not null, price numeric(10,2) not null check(price >= 0), is_active boolean not null default true, display_order int not null default 0, unique(service_id,name));
create table if not exists public.hm_payment_methods (id uuid primary key default gen_random_uuid(), name text not null, handle text, email text, phone text, payment_url text, deep_link text, instructions text, is_active boolean not null default false, display_order int not null default 0);
create table if not exists public.hm_blocked_dates (id uuid primary key default gen_random_uuid(), blocked_date date not null unique, reason text);
create table if not exists public.hm_bookings (id uuid primary key default gen_random_uuid(), booking_number text unique not null default ('HM-' || lpad((floor(random()*90000)+10000)::text,5,'0')), customer_id uuid not null references public.hm_customers(id) on delete restrict, service_id uuid not null references public.hm_services(id) on delete restrict, service_name_snapshot text not null, length_name_snapshot text not null, appointment_date date not null, appointment_time time not null, duration_minutes int not null, total_price numeric(10,2) not null, reservation_fee numeric(10,2) not null default 20, remaining_balance numeric(10,2) not null, payment_method_id uuid references public.hm_payment_methods(id) on delete set null, payment_status public.hm_payment_status not null default 'unpaid', status public.hm_booking_status not null default 'pending_payment', customer_notes text, access_token_hash text not null unique, token_expires_at timestamptz not null default(now()+interval '90 days'), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), confirmed_at timestamptz, unique(appointment_date,appointment_time));
create table if not exists public.hm_payments (id uuid primary key default gen_random_uuid(), booking_id uuid not null references public.hm_bookings(id) on delete cascade, amount numeric(10,2) not null, method_id uuid references public.hm_payment_methods(id) on delete set null, status public.hm_payment_status not null default 'unpaid', submitted_at timestamptz, verified_at timestamptz, verified_by uuid references auth.users(id) on delete set null, note text, created_at timestamptz not null default now());
create table if not exists public.hm_contact_messages (id uuid primary key default gen_random_uuid(), name text not null, email text not null, phone text, topic text not null, message text not null, booking_number text, is_read boolean not null default false, archived_at timestamptz, created_at timestamptz not null default now());

alter table public.hm_customers enable row level security; alter table public.hm_service_categories enable row level security; alter table public.hm_services enable row level security; alter table public.hm_service_lengths enable row level security; alter table public.hm_payment_methods enable row level security; alter table public.hm_blocked_dates enable row level security; alter table public.hm_bookings enable row level security; alter table public.hm_payments enable row level security; alter table public.hm_contact_messages enable row level security;
create policy "public read active hm categories" on public.hm_service_categories for select to anon,authenticated using(is_active);
create policy "public read active hm services" on public.hm_services for select to anon,authenticated using(is_active);
create policy "public read active hm lengths" on public.hm_service_lengths for select to anon,authenticated using(is_active);
create policy "public read active hm payment methods" on public.hm_payment_methods for select to anon,authenticated using(is_active);
create policy "hm admins manage categories" on public.hm_service_categories for all to authenticated using((select auth.uid()) is not null) with check((select auth.uid()) is not null);
create policy "hm admins manage services" on public.hm_services for all to authenticated using((select auth.uid()) is not null) with check((select auth.uid()) is not null);
create policy "hm admins manage lengths" on public.hm_service_lengths for all to authenticated using((select auth.uid()) is not null) with check((select auth.uid()) is not null);
create policy "hm admins manage payments" on public.hm_payment_methods for all to authenticated using((select auth.uid()) is not null) with check((select auth.uid()) is not null);
create policy "hm admins manage bookings" on public.hm_bookings for all to authenticated using((select auth.uid()) is not null) with check((select auth.uid()) is not null);
create policy "hm admins manage payment records" on public.hm_payments for all to authenticated using((select auth.uid()) is not null) with check((select auth.uid()) is not null);
create policy "hm admins manage customers" on public.hm_customers for all to authenticated using((select auth.uid()) is not null) with check((select auth.uid()) is not null);
create policy "hm admins manage contacts" on public.hm_contact_messages for all to authenticated using((select auth.uid()) is not null) with check((select auth.uid()) is not null);

insert into public.hm_service_categories(name,slug,display_order) values ('Braids','braids',1),('Twists','twists',2),('Locs','locs',3) on conflict(slug) do nothing;
insert into public.hm_services(category_id,name,slug,description,duration_minutes,image_path,display_order) values ((select id from public.hm_service_categories where slug='twists'),'Senegalese Twist','senegalese-twist','Detailed, long-lasting twists tailored to you.',240,'assets/service-senegalese.png',1),((select id from public.hm_service_categories where slug='braids'),'Boho Knotless','boho-knotless','Soft, lightweight knotless braids with a lived-in finish.',300,'assets/gallery-1.png',2),((select id from public.hm_service_categories where slug='locs'),'Soft Locs','soft-locs','Protective soft locs with a polished, natural finish.',300,'assets/gallery-2.png',3) on conflict(slug) do nothing;
insert into public.hm_service_lengths(service_id,name,price,display_order) select s.id,x.name,x.price,x.ord from public.hm_services s cross join(values('Bob',200,1),('Middle',230,2),('Waist',260,3),('Butt',300,4))x(name,price,ord) where s.slug='senegalese-twist' on conflict(service_id,name)do nothing;
insert into public.hm_service_lengths(service_id,name,price,display_order) select s.id,x.name,x.price,x.ord from public.hm_services s cross join(values('Bob',180,1),('Middle',210,2),('Waist',240,3))x(name,price,ord) where s.slug='boho-knotless' on conflict(service_id,name)do nothing;
insert into public.hm_service_lengths(service_id,name,price,display_order) select s.id,x.name,x.price,x.ord from public.hm_services s cross join(values('Bob',220,1),('Middle',250,2),('Waist',280,3))x(name,price,ord) where s.slug='soft-locs' on conflict(service_id,name)do nothing;
insert into public.hm_payment_methods(name,is_active,display_order) values('PayPal',false,1),('Zelle',false,2),('Cash App',false,3) on conflict do nothing;
